### ISSUE TITLE
Next.js 에서 실행 시  window is not defined 에러

### ISSUE THREAD

**Issue by hhhhailey** [qqww08/react-dynamic-bottom-sheet#2]
next js 버전 14.0.4 에서 실행 시  window is not defined 에러가 납니다.
![image](https://github.com/qqww08/react-dynamic-bottom-sheet/assets/25955165/f95caeeb-9a29-473f-b900-11d86121c441)

**Comment by qqww08** [comment]
제보 감사합니다! [2.1.0](https://github.com/qqww08/react-dynamic-bottom-sheet/releases/tag/v2.1.0) 에서 해결되었습니다.
